/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poly.ui;

import com.poly.utils.Auth;
import com.poly.utils.DialogHelper;
import com.poly.utils.XImage;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

/**
 *
 * @author ADMIN
 */
public class GiaoDienQuanLyKhachSan extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyThuVien
     */
    public GiaoDienQuanLyKhachSan() {
        initComponents();
        init();
    }

    void dongho() {
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                SimpleDateFormat formatter = new SimpleDateFormat("hh:mm:ss a");
                String text = formatter.format(date);
                lblDongHo.setText(text);
            }
        }).start();
    }

    void init() {
        this.setLocationRelativeTo(null);
        dongho();
        setIconImage(XImage.getAppIcon());
        new DangNhapJDialog(this, true).setVisible(true);
        lblTenTaiKhoan.setText("Xin chào, " +Auth.user.getTenTaiKhoan());
    }

    
     void openKeToan() {
        if (Auth.isLogin()) {
            new GiaoDienKeToan().setVisible(true);
        } else {
            DialogHelper.alert(this, "Bạn chưa đăng nhập!");
        }
    }
     
     void openQuanLy() {
        if (Auth.isLogin()) {
            new GiaoDienQuanLy().setVisible(true);
        } else {
            DialogHelper.alert(this, "Bạn chưa đăng nhập!");
        }
    }
     
    void openLeTan() {
        if (Auth.isLogin()) {
            new GiaoDienLeTan().setVisible(true);
        } else {
            DialogHelper.alert(this, "Bạn chưa đăng nhập!");
        }
    }
     
    
     


    void ketThuc() {
        if (DialogHelper.confirm(this, "Bạn có muốn thoát khỏi ứng dụng không?")) {
            System.exit(0);
        }
    }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDongHo = new javax.swing.JLabel();
        lblTenTaiKhoan = new javax.swing.JLabel();
        lblQuanLy = new javax.swing.JLabel();
        lblKeToan = new javax.swing.JLabel();
        lblLeTan = new javax.swing.JLabel();
        lblHinhNen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniDangXuat = new javax.swing.JMenuItem();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        mniDangKy = new javax.swing.JMenuItem();
        mniKetThuc = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniTaiKhoan = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniLienHe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Khách Sạn");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDongHo.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(255, 0, 0));
        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Alarm.png"))); // NOI18N
        getContentPane().add(lblDongHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 700, 170, 40));

        lblTenTaiKhoan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTenTaiKhoan.setForeground(new java.awt.Color(255, 0, 0));
        lblTenTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Funny.png"))); // NOI18N
        getContentPane().add(lblTenTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 240, 30));

        lblQuanLy.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblQuanLy.setText("QUẢN LÝ");
        lblQuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyMouseExited(evt);
            }
        });
        getContentPane().add(lblQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        lblKeToan.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblKeToan.setText("KẾ TOÁN");
        lblKeToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKeToanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblKeToanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblKeToanMouseExited(evt);
            }
        });
        getContentPane().add(lblKeToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 570, -1, -1));

        lblLeTan.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblLeTan.setText("LỄ TÂN");
        lblLeTan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLeTanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLeTanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLeTanMouseExited(evt);
            }
        });
        getContentPane().add(lblLeTan, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, -1));

        lblHinhNen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Hinhnenchonvaitro.png"))); // NOI18N
        getContentPane().add(lblHinhNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1150, 770));

        jMenu1.setText("Hệ thống");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Log out.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mniDangXuat);

        mniDoiMatKhau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mniDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Refresh.png"))); // NOI18N
        mniDoiMatKhau.setText("Đổi mật khẩu");
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        jMenu1.add(mniDoiMatKhau);

        mniDangKy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangKy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mniDangKy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Create.png"))); // NOI18N
        mniDangKy.setText("Đăng ký");
        mniDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangKyActionPerformed(evt);
            }
        });
        jMenu1.add(mniDangKy);

        mniKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniKetThuc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mniKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Stop.png"))); // NOI18N
        mniKetThuc.setText("Kết thúc");
        mniKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKetThucActionPerformed(evt);
            }
        });
        jMenu1.add(mniKetThuc);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Tài khoản");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mniTaiKhoan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mniTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Microsoft.png"))); // NOI18N
        mniTaiKhoan.setText("Quản lý tài khoản");
        mniTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTaiKhoanActionPerformed(evt);
            }
        });
        jMenu3.add(mniTaiKhoan);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Trợ giúp");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mniLienHe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniLienHe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mniLienHe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Brick house.png"))); // NOI18N
        mniLienHe.setText("Địa chỉ liên hệ");
        mniLienHe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLienHeActionPerformed(evt);
            }
        });
        jMenu2.add(mniLienHe);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
      //  dangXuat();
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
       
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void mniKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKetThucActionPerformed
        ketThuc();
    }//GEN-LAST:event_mniKetThucActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.NO_OPTION) {
                setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            }else{
                System.exit(0);
            }
    }//GEN-LAST:event_formWindowClosing

    private void mniDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangKyActionPerformed
      //  openDangKy(1);
    }//GEN-LAST:event_mniDangKyActionPerformed

    private void mniTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTaiKhoanActionPerformed
      //  openQLTaiKhoan(1);
    }//GEN-LAST:event_mniTaiKhoanActionPerformed

    private void mniLienHeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLienHeActionPerformed
         DialogHelper.alert(this, "Mọi chi tiết gửi về Email: hoahonghotel@gmail.com");
    }//GEN-LAST:event_mniLienHeActionPerformed

    private void lblQuanLyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyMouseClicked
       openQuanLy();
    }//GEN-LAST:event_lblQuanLyMouseClicked

    private void lblQuanLyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyMouseEntered
        lblQuanLy.setText("<html><b>QUẢN LÝ</b></html>");
        lblQuanLy.setForeground(Color.red);
    }//GEN-LAST:event_lblQuanLyMouseEntered

    private void lblQuanLyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyMouseExited
        lblQuanLy.setText("<html>QUẢN LÝ</html>");
        lblQuanLy.setForeground(Color.black);
    }//GEN-LAST:event_lblQuanLyMouseExited

    private void lblKeToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKeToanMouseClicked
       openKeToan();
    }//GEN-LAST:event_lblKeToanMouseClicked

    private void lblKeToanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKeToanMouseEntered
        lblKeToan.setText("<html><b>KẾ TOÁN</b></html>");
        lblKeToan.setForeground(Color.red);
    }//GEN-LAST:event_lblKeToanMouseEntered

    private void lblKeToanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKeToanMouseExited
        lblKeToan.setText("<html>KẾ TOÁN</html>");
        lblKeToan.setForeground(Color.black);
    }//GEN-LAST:event_lblKeToanMouseExited

    private void lblLeTanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLeTanMouseExited
        lblLeTan.setText("<html>LỄ TÂN</html>");
        lblLeTan.setForeground(Color.black);
    }//GEN-LAST:event_lblLeTanMouseExited

    private void lblLeTanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLeTanMouseEntered
        lblLeTan.setText("<html><b>LỄ TÂN</b></html>");
        lblLeTan.setForeground(Color.red);
    }//GEN-LAST:event_lblLeTanMouseEntered

    private void lblLeTanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLeTanMouseClicked
        openLeTan();
    }//GEN-LAST:event_lblLeTanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLyKhachSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLyKhachSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLyKhachSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLyKhachSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienQuanLyKhachSan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblHinhNen;
    private javax.swing.JLabel lblKeToan;
    private javax.swing.JLabel lblLeTan;
    private javax.swing.JLabel lblQuanLy;
    private javax.swing.JLabel lblTenTaiKhoan;
    private javax.swing.JMenuItem mniDangKy;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniKetThuc;
    private javax.swing.JMenuItem mniLienHe;
    private javax.swing.JMenuItem mniTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
