/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poly.ui;

import com.poly.utils.Auth;
import com.poly.utils.DialogHelper;
import com.poly.utils.XImage;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

/**
 *
 * @author ADMIN
 */
public class GiaoDienQuanLy extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyThuVien
     */
    public GiaoDienQuanLy() {
        initComponents();
        init();
    }

    void dongho() {
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                SimpleDateFormat formatter = new SimpleDateFormat("hh:mm:ss a");
                String text = formatter.format(date);
                lblDongHo.setText(text);
            }
        }).start();
    }

    void init() {
        this.setLocationRelativeTo(null);
        dongho();
        setIconImage(XImage.getAppIcon());
       // new DangNhapJDialog(this, true).setVisible(true);
        lblTenTaiKhoan.setText("Xin chào, " +Auth.user.getTenTaiKhoan());
    }
     
     void openTienLuong() {
        if (Auth.isLogin()) {
            new QuanLyTienLuong().setVisible(true);
        } else {
            DialogHelper.alert(this, "Bạn chưa đăng nhập!");
        }
    }
     
     void openXemCaLamViec() {
        if (Auth.isLogin()) {
            new XemCaLamViec().setVisible(true);
        } else {
            DialogHelper.alert(this, "Bạn chưa đăng nhập!");
        }
    }
     
     
      void openThongKe() {
        if (Auth.isLogin()) {
            new ThongKe().setVisible(true);
        } else {
            DialogHelper.alert(this, "Bạn chưa đăng nhập!");
        }
    }
     
//     void dangXuat() {
//        if (Auth.isLogin()) {
//            Auth.dangXuat();
//            new DangNhapJDialog(this, true).setVisible(true);
//            lblTenTaiKhoan.setText("Xin chào, " +Auth.user.getTenTaiKhoan());
//            checkopenNhanVien();
//           // checkopenThongKe();
//        } else {
//            DialogHelper.alert(this, "Bạn chưa đăng nhập!");
//            new DangNhapJDialog(this, true).setVisible(true);
//        }
//    }
     
     void openDoiMatKhau() {
        if (Auth.isLogin()) {
            new DoiMatKhau().setVisible(true);
        } else {
            DialogHelper.alert(this, "Bạn chưa đăng nhập");
        }
    }
     
//     void openDangKy(int index) {
//        if (Auth.isLogin()) {
//            if (index == 1 && !Auth.isManager()) {
//                DialogHelper.alert(this, "Bạn không có quyền đăng ký tài khoản");
//            } else {
//                DangKy dk = new DangKy();
//                dk.setVisible(true);
//            }
//        } else {
//            DialogHelper.alert(this, "Bạn chưa đăng nhập!");
//        }
//    }
     
//    void openQLTaiKhoan(int index) {
//        if (Auth.isLogin()) {
//            if (index == 1 && !Auth.isManager()) {
//                DialogHelper.alert(this, "Bạn không có quyền quản lý tài khoản");
//            } else {
//                QuanLyTaiKhoan qltk = new QuanLyTaiKhoan();
//                qltk.setVisible(true);
//            }
//        } else {
//            DialogHelper.alert(this, "Bạn chưa đăng nhập!");
//        }
//    }

    void ketThuc() {
        if (DialogHelper.confirm(this, "Bạn có muốn thoát khỏi ứng dụng không?")) {
            System.exit(0);
        }
    }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSapXepCaLam = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblLuong = new javax.swing.JLabel();
        lblCapTaiKhoan = new javax.swing.JLabel();
        lblQuanLyDichVu = new javax.swing.JLabel();
        lblThongKe = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        lblTenTaiKhoan = new javax.swing.JLabel();
        lblLichSu = new javax.swing.JLabel();
        lblXemThongKe = new javax.swing.JLabel();
        lblPhong = new javax.swing.JLabel();
        lblHinhNen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniDangXuat = new javax.swing.JMenuItem();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        mniDangKy = new javax.swing.JMenuItem();
        mniKetThuc = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniTaiKhoan = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniLienHe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Khách Sạn");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSapXepCaLam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSapXepCaLam.setText("SẮP XẾP CA LÀM");
        lblSapXepCaLam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSapXepCaLamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSapXepCaLamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSapXepCaLamMouseExited(evt);
            }
        });
        getContentPane().add(lblSapXepCaLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        lblNhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNhanVien.setText("NHÂN VIÊN");
        lblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNhanVienMouseExited(evt);
            }
        });
        getContentPane().add(lblNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        lblLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLuong.setText("TIỀN LƯƠNG");
        lblLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLuongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLuongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLuongMouseExited(evt);
            }
        });
        getContentPane().add(lblLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, -1, -1));

        lblCapTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCapTaiKhoan.setText("CẤP TÀI KHOẢN");
        lblCapTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCapTaiKhoanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCapTaiKhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCapTaiKhoanMouseExited(evt);
            }
        });
        getContentPane().add(lblCapTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 140, 50));

        lblQuanLyDichVu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblQuanLyDichVu.setText("QUẢN LÝ DỊCH VỤ");
        lblQuanLyDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyDichVuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyDichVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyDichVuMouseExited(evt);
            }
        });
        getContentPane().add(lblQuanLyDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, 30));

        lblThongKe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblThongKe.setText("THỐNG KÊ");
        lblThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThongKeMouseExited(evt);
            }
        });
        getContentPane().add(lblThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 570, -1, -1));

        lblDongHo.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(255, 0, 0));
        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Alarm.png"))); // NOI18N
        getContentPane().add(lblDongHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 700, 170, 40));

        lblTenTaiKhoan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTenTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        lblTenTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Funny.png"))); // NOI18N
        getContentPane().add(lblTenTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, 30));

        lblLichSu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLichSu.setText("LỊCH SỬ PHÒNG");
        lblLichSu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLichSuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLichSuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLichSuMouseExited(evt);
            }
        });
        getContentPane().add(lblLichSu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 590, -1, -1));

        lblXemThongKe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblXemThongKe.setText("THỐNG KÊ");
        lblXemThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXemThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblXemThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblXemThongKeMouseExited(evt);
            }
        });
        getContentPane().add(lblXemThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 580, -1, -1));

        lblPhong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPhong.setText("QUẢN LÝ PHÒNG");
        lblPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPhongMouseExited(evt);
            }
        });
        getContentPane().add(lblPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 190, -1, -1));

        lblHinhNen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/giaodienchinhQuanly.png"))); // NOI18N
        getContentPane().add(lblHinhNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1150, 770));

        jMenu1.setText("Hệ thống");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Log out.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mniDangXuat);

        mniDoiMatKhau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mniDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Refresh.png"))); // NOI18N
        mniDoiMatKhau.setText("Đổi mật khẩu");
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        jMenu1.add(mniDoiMatKhau);

        mniDangKy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangKy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mniDangKy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Create.png"))); // NOI18N
        mniDangKy.setText("Đăng ký");
        mniDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangKyActionPerformed(evt);
            }
        });
        jMenu1.add(mniDangKy);

        mniKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniKetThuc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mniKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Stop.png"))); // NOI18N
        mniKetThuc.setText("Kết thúc");
        mniKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKetThucActionPerformed(evt);
            }
        });
        jMenu1.add(mniKetThuc);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Tài khoản");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mniTaiKhoan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mniTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Microsoft.png"))); // NOI18N
        mniTaiKhoan.setText("Quản lý tài khoản");
        mniTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTaiKhoanActionPerformed(evt);
            }
        });
        jMenu3.add(mniTaiKhoan);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Trợ giúp");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mniLienHe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniLienHe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mniLienHe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Brick house.png"))); // NOI18N
        mniLienHe.setText("Địa chỉ liên hệ");
        mniLienHe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLienHeActionPerformed(evt);
            }
        });
        jMenu2.add(mniLienHe);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSapXepCaLamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSapXepCaLamMouseClicked
       // openNhanVien(1);
        openXemCaLamViec();
    }//GEN-LAST:event_lblSapXepCaLamMouseClicked

    private void lblSapXepCaLamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSapXepCaLamMouseEntered
        lblSapXepCaLam.setText("<html><b>SẮP XẾP CA LÀM</b></html>");
        lblSapXepCaLam.setForeground(Color.red);
    }//GEN-LAST:event_lblSapXepCaLamMouseEntered

    private void lblSapXepCaLamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSapXepCaLamMouseExited
        lblSapXepCaLam.setText("<html>SẮP XẾP CA LÀM</html>");
        lblSapXepCaLam.setForeground(Color.black);
    }//GEN-LAST:event_lblSapXepCaLamMouseExited

    private void lblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienMouseClicked
        
    }//GEN-LAST:event_lblNhanVienMouseClicked

    private void lblNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienMouseEntered
        lblNhanVien.setText("<html><b>NHÂN VIÊN</b></html>");
        lblNhanVien.setForeground(Color.red);
    }//GEN-LAST:event_lblNhanVienMouseEntered

    private void lblNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienMouseExited
        lblNhanVien.setText("<html>NHÂN VIÊN</html>");
        lblNhanVien.setForeground(Color.black);
    }//GEN-LAST:event_lblNhanVienMouseExited

    private void lblLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLuongMouseClicked
        openTienLuong();
    }//GEN-LAST:event_lblLuongMouseClicked

    private void lblLuongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLuongMouseEntered
        lblLuong.setText("<html><b>TIỀN LƯƠNG</b></html>");
        lblLuong.setForeground(Color.red);
    }//GEN-LAST:event_lblLuongMouseEntered

    private void lblLuongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLuongMouseExited
        lblLuong.setText("<html>TIỀN LƯƠNG</html>");
        lblLuong.setForeground(Color.black);
    }//GEN-LAST:event_lblLuongMouseExited

    private void lblCapTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCapTaiKhoanMouseClicked
        
    }//GEN-LAST:event_lblCapTaiKhoanMouseClicked

    private void lblCapTaiKhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCapTaiKhoanMouseEntered
        lblCapTaiKhoan.setText("<html><b>CẤP TÀI KHOẢN</b></html>");
        lblCapTaiKhoan.setForeground(Color.red);
    }//GEN-LAST:event_lblCapTaiKhoanMouseEntered

    private void lblCapTaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCapTaiKhoanMouseExited
        lblCapTaiKhoan.setText("<html>CẤP TÀI KHOẢN</html>");
        lblCapTaiKhoan.setForeground(Color.black);
    }//GEN-LAST:event_lblCapTaiKhoanMouseExited

    private void lblQuanLyDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyDichVuMouseClicked
        
    }//GEN-LAST:event_lblQuanLyDichVuMouseClicked

    private void lblQuanLyDichVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyDichVuMouseEntered
        lblQuanLyDichVu.setText("<html><b>DỊCH VỤ</b></html>");
        lblQuanLyDichVu.setForeground(Color.red);
    }//GEN-LAST:event_lblQuanLyDichVuMouseEntered

    private void lblQuanLyDichVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyDichVuMouseExited
        lblQuanLyDichVu.setText("<html>DỊCH VỤ</html>");
        lblQuanLyDichVu.setForeground(Color.black);
    }//GEN-LAST:event_lblQuanLyDichVuMouseExited

    private void lblThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseClicked
        openThongKe();
    }//GEN-LAST:event_lblThongKeMouseClicked

    private void lblThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseEntered
        lblThongKe.setText("<html><b>THỐNG KÊ</b></html>");
        lblThongKe.setForeground(Color.red);
    }//GEN-LAST:event_lblThongKeMouseEntered

    private void lblThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseExited
        lblThongKe.setText("<html>THỐNG KÊ</html>");
        lblThongKe.setForeground(Color.black);
    }//GEN-LAST:event_lblThongKeMouseExited

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
      //  dangXuat();
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
        openDoiMatKhau();
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void mniKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKetThucActionPerformed
        ketThuc();
    }//GEN-LAST:event_mniKetThucActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.NO_OPTION) {
                setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            }else{
                System.exit(0);
            }
    }//GEN-LAST:event_formWindowClosing

    private void mniDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangKyActionPerformed
      //  openDangKy(1);
    }//GEN-LAST:event_mniDangKyActionPerformed

    private void mniTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTaiKhoanActionPerformed
      //  openQLTaiKhoan(1);
    }//GEN-LAST:event_mniTaiKhoanActionPerformed

    private void mniLienHeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLienHeActionPerformed
         DialogHelper.alert(this, "Mọi chi tiết gửi về Email: hoahonghotel@gmail.com");
    }//GEN-LAST:event_mniLienHeActionPerformed

    private void lblPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhongMouseClicked
        
    }//GEN-LAST:event_lblPhongMouseClicked

    private void lblPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhongMouseEntered
        lblPhong.setText("<html><b>QUẢN LÝ PHÒNG</b></html>");
        lblPhong.setForeground(Color.red);
    }//GEN-LAST:event_lblPhongMouseEntered

    private void lblPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhongMouseExited
        lblPhong.setText("<html>QUẢN LÝ PHÒNG</html>");
        lblPhong.setForeground(Color.black);
    }//GEN-LAST:event_lblPhongMouseExited

    private void lblLichSuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLichSuMouseClicked
        
    }//GEN-LAST:event_lblLichSuMouseClicked

    private void lblLichSuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLichSuMouseEntered
        lblLichSu.setText("<html><b>LỊCH SỬ PHÒNG</b></html>");
        lblLichSu.setForeground(Color.red);
    }//GEN-LAST:event_lblLichSuMouseEntered

    private void lblLichSuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLichSuMouseExited
        lblLichSu.setText("<html>LỊCH SỬ PHÒNG</html>");
        lblLichSu.setForeground(Color.black);
    }//GEN-LAST:event_lblLichSuMouseExited

    private void lblXemThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXemThongKeMouseClicked
        
    }//GEN-LAST:event_lblXemThongKeMouseClicked

    private void lblXemThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXemThongKeMouseEntered
        lblXemThongKe.setText("<html><b>THỐNG KÊ</b></html>");
        lblXemThongKe.setForeground(Color.red);
    }//GEN-LAST:event_lblXemThongKeMouseEntered

    private void lblXemThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXemThongKeMouseExited
        lblXemThongKe.setText("<html>THỐNG KÊ</html>");
        lblXemThongKe.setForeground(Color.black);
    }//GEN-LAST:event_lblXemThongKeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblCapTaiKhoan;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblHinhNen;
    private javax.swing.JLabel lblLichSu;
    private javax.swing.JLabel lblLuong;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblPhong;
    private javax.swing.JLabel lblQuanLyDichVu;
    private javax.swing.JLabel lblSapXepCaLam;
    private javax.swing.JLabel lblTenTaiKhoan;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblXemThongKe;
    private javax.swing.JMenuItem mniDangKy;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniKetThuc;
    private javax.swing.JMenuItem mniLienHe;
    private javax.swing.JMenuItem mniTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
