/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poly.ui;

import com.poly.dao.ChiPhiHangNgayDAO;
import com.poly.dao.ChiPhiThangDAO;
import com.poly.dao.DoanhThuThangDAO;
import com.poly.dao.ThongKeDAO;
import com.poly.entity.DoanhThuThang;
import com.poly.utils.DialogHelper;
import com.poly.utils.XImage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class ThongKe extends javax.swing.JFrame {

    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
        init();
    }

    DoanhThuThangDAO dttdao = new DoanhThuThangDAO();
    ThongKeDAO tkdao = new ThongKeDAO();
    int row = -1;

    void init() {
        setLocationRelativeTo(null);
        setIconImage(XImage.getAppIcon());
        setDefaultCloseOperation(ThongKe.this.DISPOSE_ON_CLOSE);
        fillTableDoanhThu();
        fillTableChiPhi();
    }

    void fillTableDoanhThu() {
        String header[] = {"Mã DTT", "Mã NV", "Tháng", "Năm", "Tổng Doanh Thu"};
        DefaultTableModel model = new DefaultTableModel(header, 0);
        try {
            List<DoanhThuThang> list = dttdao.select();
            for (DoanhThuThang dtt : list) {
                model.addRow(new Object[]{
                    dtt.getMaDoanhThuThang(), dtt.getMaNhanVien(), dtt.getThang(), dtt.getNam(),
                    dtt.getTongDoanhThuNgay(), dtt.getGhiChu()});
            }
            tblThongKeDoanhThu.setModel(model);
            //Điều chỉnh độ rộng các cột
            tblThongKeDoanhThu.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblThongKeDoanhThu.getColumnModel().getColumn(1).setPreferredWidth(30);
            tblThongKeDoanhThu.getColumnModel().getColumn(2).setPreferredWidth(15);
            tblThongKeDoanhThu.getColumnModel().getColumn(3).setPreferredWidth(20);
            tblThongKeDoanhThu.getColumnModel().getColumn(4).setPreferredWidth(80);
           
            //Canh lề dữ liệu trong bảng
            DefaultTableCellRenderer canhLe = new DefaultTableCellRenderer();
            canhLe.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
            tblThongKeDoanhThu.getColumn("Mã DTT").setCellRenderer(canhLe);
            tblThongKeDoanhThu.getColumn("Mã NV").setCellRenderer(canhLe);

        } catch (Exception e) {
            System.out.println(e);
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    
     void fillTableChiPhi() {
        String header[] = {"Mã CPT", "Mã NV", "Tháng", "Năm", "Tổng Chi Phí"};
        DefaultTableModel model = new DefaultTableModel(header, 0);
        List<Object[]> list = tkdao.thongKeChiPhiThang();
        for (Object[] ob : list) {
            model.addRow(ob);
        }
        tblThongKeChiPhi.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblThongKeDoanhThu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNam = new javax.swing.JTextField();
        btnXemDoanhThuNam = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblTongDoanhThuNam = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblThongKeChiPhi = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNamCP = new javax.swing.JTextField();
        btnXemChiPhiNam = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblTongChiPhiNam = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtThangLN = new javax.swing.JTextField();
        btnXemLoiNhuanThang = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblLoiNhuanThang = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTongLNNam = new javax.swing.JTextField();
        btnXemLoiNhuanNam = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblLoiNhuanNam = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtNamLN = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thống Kê");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("THỐNG KÊ");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tblThongKeDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblThongKeDoanhThu);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("XEM TỔNG DOANH THU TRONG NĂM:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Năm:");

        btnXemDoanhThuNam.setText("Xem");
        btnXemDoanhThuNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemDoanhThuNamActionPerformed(evt);
            }
        });

        tblTongDoanhThuNam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblTongDoanhThuNam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Tổng Doanh Thu Trong Năm"
            }
        ));
        tblTongDoanhThuNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTongDoanhThuNamMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblTongDoanhThuNam);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnXemDoanhThuNam))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXemDoanhThuNam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DOANH THU", jPanel4);

        tblThongKeChiPhi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblThongKeChiPhi);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("XEM TỔNG CHI PHÍ TRONG NĂM");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Năm:");

        btnXemChiPhiNam.setText("Xem");
        btnXemChiPhiNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemChiPhiNamActionPerformed(evt);
            }
        });

        tblTongChiPhiNam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblTongChiPhiNam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Tổng Chi Phí Trong Năm"
            }
        ));
        tblTongChiPhiNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTongChiPhiNamMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tblTongChiPhiNam);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNamCP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)
                                    .addComponent(btnXemChiPhiNam))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNamCP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXemChiPhiNam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CHI PHÍ", jPanel3);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("XEM LỢI NHUẬN TRONG THÁNG");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tháng:");

        btnXemLoiNhuanThang.setText("Xem");
        btnXemLoiNhuanThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemLoiNhuanThangActionPerformed(evt);
            }
        });

        tblLoiNhuanThang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblLoiNhuanThang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Lợi Nhuận Trong Tháng"
            }
        ));
        tblLoiNhuanThang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoiNhuanThangMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(tblLoiNhuanThang);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("XEM TỔNG LỢI NHUẬN TRONG NĂM");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Năm:");

        btnXemLoiNhuanNam.setText("Xem");
        btnXemLoiNhuanNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemLoiNhuanNamActionPerformed(evt);
            }
        });

        tblLoiNhuanNam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblLoiNhuanNam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Tổng Lợi Nhuận Trong Năm"
            }
        ));
        tblLoiNhuanNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoiNhuanNamMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(tblLoiNhuanNam);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Năm:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTongLNNam, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(525, 525, 525)
                        .addComponent(btnXemLoiNhuanNam))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtThangLN, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtNamLN, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnXemLoiNhuanThang))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel6)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXemLoiNhuanThang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThangLN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(txtNamLN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTongLNNam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXemLoiNhuanNam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("LỢI NHUẬN", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTongDoanhThuNamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTongDoanhThuNamMouseClicked
       
    }//GEN-LAST:event_tblTongDoanhThuNamMouseClicked

    private void btnXemDoanhThuNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemDoanhThuNamActionPerformed
          String header[] = {"Tổng Doanh Thu Trong Năm"};
        DefaultTableModel tblModel = new DefaultTableModel(header, 0);
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        try {
            if (txtNam.getText().equals("")) {
                DialogHelper.alert(this, "Năm không được trống");
                txtNam.requestFocus();
            } else {
                String user = "sa";
                String pass = "123";
                String url = "jdbc:sqlserver://localhost:1433;databaseName=QuanLyKhachSan";
                con = DriverManager.getConnection(url, user, pass);
                String sql = "SELECT SUM(TongDoanhThuNgay) AS N'Tổng Doanh Thu Trong Năm' FROM DoanhThuThang WHERE Nam = " + txtNam.getText() + "";
                st = con.createStatement();
                rs = st.executeQuery(sql);
                Vector data = null;
                tblModel.setRowCount(0);
                while (rs.next()) {
                    data = new Vector();
                    data.add(rs.getDouble("Tổng Doanh Thu Trong Năm"));

                    tblModel.addRow(data);
                }
                tblTongDoanhThuNam.setModel(tblModel);
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Năm không hợp lệ");
        } finally {
            try {
                if (con != null) {
                    con.close();
                }
                if (st != null) {
                    st.close();
                }
                if (rs != null) {
                    rs.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnXemDoanhThuNamActionPerformed

    private void tblTongChiPhiNamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTongChiPhiNamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTongChiPhiNamMouseClicked

    private void btnXemChiPhiNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemChiPhiNamActionPerformed
          String header[] = {"Tổng Chi Phí Trong Năm"};
        DefaultTableModel tblModel = new DefaultTableModel(header, 0);
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        try {
            if (txtNamCP.getText().equals("")) {
                DialogHelper.alert(this, "Năm không được trống");
                txtNamCP.requestFocus();
            } else {
                String user = "sa";
                String pass = "123";
                String url = "jdbc:sqlserver://localhost:1433;databaseName=QuanLyKhachSan";
                con = DriverManager.getConnection(url, user, pass);
                String sql = "SELECT SUM(TongChiPhiNgay + TienDien + TienNuoc + TienLuong + TienThue + TienNhapHang) AS N'Tổng Chi Phí Trong Năm' FROM ChiPhiThang WHERE Nam = " + txtNamCP.getText() + "";
                st = con.createStatement();
                rs = st.executeQuery(sql);
                Vector data = null;
                tblModel.setRowCount(0);
                while (rs.next()) {
                    data = new Vector();
                    data.add(rs.getDouble("Tổng Chi Phí Trong Năm"));

                    tblModel.addRow(data);
                }
                tblTongChiPhiNam.setModel(tblModel);
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Năm không hợp lệ");
        } finally {
            try {
                if (con != null) {
                    con.close();
                }
                if (st != null) {
                    st.close();
                }
                if (rs != null) {
                    rs.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnXemChiPhiNamActionPerformed

    private void tblLoiNhuanThangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoiNhuanThangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLoiNhuanThangMouseClicked

    private void tblLoiNhuanNamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoiNhuanNamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLoiNhuanNamMouseClicked

    private void btnXemLoiNhuanThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemLoiNhuanThangActionPerformed
          String header[] = {"Lợi Nhuận Trong Tháng"};
        DefaultTableModel tblModel = new DefaultTableModel(header, 0);
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        try {
            if (txtThangLN.getText().equals("")) {
                DialogHelper.alert(this, "Tháng không được trống");
                txtThangLN.requestFocus();
            } else if (txtNamLN.getText().equals("")) {
                DialogHelper.alert(this, "Năm không được trống");
                txtNamLN.requestFocus();
            } else {
                String user = "sa";
                String pass = "123";
                String url = "jdbc:sqlserver://localhost:1433;databaseName=QuanLyKhachSan";
                con = DriverManager.getConnection(url, user, pass);
                String sql = "SELECT SUM(DoanhThuThang.TongDoanhThuNgay) - SUM(ChiPhiThang.TongChiPhiNgay + ChiPhiThang.TienDien + ChiPhiThang.TienNuoc + ChiPhiThang.TienLuong + ChiPhiThang.TienThue + ChiPhiThang.TienNhapHang) AS N'Lợi Nhuận Trong Tháng' \n" +
                              "FROM DoanhThuThang INNER JOIN ChiPhiThang ON DoanhThuThang.MaNV = ChiPhiThang.MaNV WHERE DoanhThuThang.Thang = " + txtThangLN.getText() + " AND DoanhThuThang.Nam = " + txtNamLN.getText() + "";
                st = con.createStatement();
                rs = st.executeQuery(sql);
                Vector data = null;
                tblModel.setRowCount(0);
                while (rs.next()) {
                    data = new Vector();
                    data.add(rs.getDouble("Lợi Nhuận Trong Tháng"));

                    tblModel.addRow(data);
                }
                tblLoiNhuanThang.setModel(tblModel);
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Tháng hoặc Năm không hợp lệ");
        } finally {
            try {
                if (con != null) {
                    con.close();
                }
                if (st != null) {
                    st.close();
                }
                if (rs != null) {
                    rs.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnXemLoiNhuanThangActionPerformed

    private void btnXemLoiNhuanNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemLoiNhuanNamActionPerformed
          String header[] = {"Tổng Lợi Nhuận Trong Năm"};
        DefaultTableModel tblModel = new DefaultTableModel(header, 0);
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        try {
             if (txtTongLNNam.getText().equals("")) {
                DialogHelper.alert(this, "Năm không được trống");
                txtTongLNNam.requestFocus();
            } else {
                String user = "sa";
                String pass = "123";
                String url = "jdbc:sqlserver://localhost:1433;databaseName=QuanLyKhachSan";
                con = DriverManager.getConnection(url, user, pass);
                String sql = "SELECT SUM(DoanhThuThang.TongDoanhThuNgay) - SUM(ChiPhiThang.TongChiPhiNgay + ChiPhiThang.TienDien + ChiPhiThang.TienNuoc + ChiPhiThang.TienLuong + ChiPhiThang.TienThue + ChiPhiThang.TienNhapHang) AS N'Tổng Lợi Nhuận Trong Năm' \n" +
                              "FROM DoanhThuThang INNER JOIN ChiPhiThang ON DoanhThuThang.MaNV = ChiPhiThang.MaNV WHERE DoanhThuThang.Nam = " + txtTongLNNam.getText() + "";
                st = con.createStatement();
                rs = st.executeQuery(sql);
                Vector data = null;
                tblModel.setRowCount(0);
                while (rs.next()) {
                    data = new Vector();
                    data.add(rs.getDouble("Tổng Lợi Nhuận Trong Năm"));

                    tblModel.addRow(data);
                }
                tblLoiNhuanNam.setModel(tblModel);
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Năm không hợp lệ" +e);
        } finally {
            try {
                if (con != null) {
                    con.close();
                }
                if (st != null) {
                    st.close();
                }
                if (rs != null) {
                    rs.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnXemLoiNhuanNamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXemChiPhiNam;
    private javax.swing.JButton btnXemDoanhThuNam;
    private javax.swing.JButton btnXemLoiNhuanNam;
    private javax.swing.JButton btnXemLoiNhuanThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblLoiNhuanNam;
    private javax.swing.JTable tblLoiNhuanThang;
    private javax.swing.JTable tblThongKeChiPhi;
    private javax.swing.JTable tblThongKeDoanhThu;
    private javax.swing.JTable tblTongChiPhiNam;
    private javax.swing.JTable tblTongDoanhThuNam;
    private javax.swing.JTextField txtNam;
    private javax.swing.JTextField txtNamCP;
    private javax.swing.JTextField txtNamLN;
    private javax.swing.JTextField txtThangLN;
    private javax.swing.JTextField txtTongLNNam;
    // End of variables declaration//GEN-END:variables
}
